@extends('layouts.app')
@section('content')
<nav class="primary-nav" data-primary-nav aria-label="Menu layanan utama"><a class="primary-brand" href="{{ route('home') }}"><span class="brand-mark">ds</span><span>KSP Dharma Siaga</span></a><button class="menu-toggle" type="button" aria-label="Buka menu" aria-expanded="false" data-menu-toggle>☰</button><div class="primary-links"><a href="{{ route('home') }}">Beranda</a><a href="#about">Tentang Kami</a><a href="#asset-overview">Produk</a><a href="#about">Galeri</a><a href="#contact">Kontak</a></div><span class="primary-actions"><button class="lang-toggle" type="button" data-lang-toggle aria-pressed="false">EN</button><a class="button button-small" href="#contact"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M4 12h13M13 6l6 6-6 6"/></svg>Menjadi anggota</a></span></nav>
<main id="main-content">
  <section class="hero" aria-label="Pengantar koperasi">
    <div class="hero-copy"><p class="eyebrow">Koperasi anggota, untuk pertumbuhan bersama</p><h1 data-id="Tumbuh bersama, dengan cara yang lebih adil." data-en="Grow together, in a fairer way.">Tumbuh bersama, dengan cara yang lebih adil.</h1><p class="hero-text" data-id="Ruang tumbuh mempertemukan simpanan anggota, pembiayaan yang bertanggung jawab, dan jejaring usaha lokal." data-en="Ruang Tumbuh brings together member savings, responsible financing, and local business networks.">Ruang tumbuh mempertemukan simpanan anggota, pembiayaan yang bertanggung jawab, dan jejaring usaha lokal.</p><div class="hero-actions"><a class="button" href="#membership">Mulai dari keanggotaan</a><a class="text-link" href="#assets">Lihat ringkasan aset <span aria-hidden="true">↘</span></a></div></div>
    <div class="hero-art"><div class="sun-disc"></div><div class="hero-note"><span class="note-label">Catatan anggota / 04</span><strong>Modal yang berputar, manfaat yang kembali.</strong><span>Transparan sejak setoran pertama.</span></div><div class="hero-stamp">RT<br><small>koperasi</small></div></div>
    <div class="carousel-controls"><button type="button" aria-label="Slide sebelumnya" data-slide-prev>←</button><span><b data-slide-current>01</b> / 03</span><button type="button" aria-label="Slide berikutnya" data-slide-next>→</button></div>
  </section>
  @include('partials.service-highlights')
  @include('partials.asset-overview')
  @include('partials.member-benefits')
  @include('partials.about-video')
  <section id="assets" class="asset-section section"><div class="section-kicker">01 / ringkasan terbuka</div><div class="asset-heading"><h2>Yang kami kelola, <em>bersama.</em></h2><p>Ringkasan ini membantu anggota memahami ke mana kontribusi mereka bergerak. Angka final dikelola melalui CMS dan laporan resmi koperasi.</p></div><div class="asset-table" role="table"><div class="asset-row asset-head" role="row"><span>Pos aset</span><span>Peran</span><span>Status</span></div><div class="asset-row" role="row"><strong>Simpanan anggota</strong><span>Modal dasar layanan</span><span class="status">Aktif</span></div><div class="asset-row" role="row"><strong>Pembiayaan usaha</strong><span>Dana tumbuh di komunitas</span><span class="status">Bergulir</span></div><div class="asset-row" role="row"><strong>Dana sosial</strong><span>Penopang kebutuhan bersama</span><span class="status status-muted">Dilaporkan berkala</span></div></div></section>
  <section id="about" class="about-section section"><div class="about-quote"><span class="quote-mark">“</span><p>Ketika anggota punya ruang untuk menyimpan, meminjam, dan berjejaring, pertumbuhan tidak perlu meninggalkan siapa pun.</p></div><div class="about-copy"><div class="section-kicker">02 / tentang ruang tumbuh</div><h2>Koperasi dengan <em>pintu yang terbuka.</em></h2><p>Kami membangun layanan keuangan yang dekat dengan keputusan sehari-hari anggota. Setiap produk dirancang agar mudah dipahami, bisa diawasi, dan kembali memberi nilai ke komunitas.</p><a class="text-link" href="#partners">Kenali ekosistem kami <span aria-hidden="true">↘</span></a></div></section>
  <section id="benefits" class="benefit-section section"><div class="section-kicker">03 / nilai keanggotaan</div><div class="benefit-intro"><h2>Satu kartu anggota,<br><em>banyak jalan tumbuh.</em></h2><p>Keanggotaan memberi akses pada layanan yang saling terhubung, bukan sekadar rekening.</p></div><div class="benefit-list"><article><span>01</span><div><h3>Simpanan yang jelas</h3><p>Pantau kontribusi, pembagian manfaat, dan laporan dengan bahasa yang mudah.</p></div></article><article><span>02</span><div><h3>Jejaring usaha</h3><p>Temukan partner dan pengetahuan yang membantu usaha anggota bergerak.</p></div></article><article><span>03</span><div><h3>Suara di meja keputusan</h3><p>Ikut menyampaikan aspirasi dan memilih arah layanan koperasi.</p></div></article></div></section>
  <section id="partners" class="partners-section section"><div class="section-kicker">04 / mitra</div><div class="partner-grid"><div><h2>Belajar dari yang <em>sejalan.</em></h2><p>Kami bekerja dengan mitra finansial dan non-finansial yang punya komitmen pada ekonomi anggota.</p></div><div class="partner-column"><h3>Finansial</h3><p class="partner-name">Lembaga pembiayaan anggota</p><p class="partner-name">Kanal pembayaran bersama</p></div><div class="partner-column"><h3>Non-finansial</h3><p class="partner-name">Pendamping usaha lokal</p><p class="partner-name">Komunitas dan institusi belajar</p></div></div></section>
  <section id="branches" class="branch-section section"><div class="section-kicker">05 / kantor cabang</div><div class="branch-head"><h2>Datang dan <em>berbincang.</em></h2><p>Temui tim kami di titik layanan terdekat. Jam buka dan kontak dapat diperbarui dari CMS.</p></div><div class="branch-grid"><article><span>Jakarta Selatan</span><h3>Ruang Tumbuh Kemang</h3><p>Senin–Jumat, 09.00–16.00</p><a href="https://maps.google.com/?q=Kemang+Jakarta" target="_blank" rel="noreferrer">Buka peta ↗</a></article><article><span>Bandung</span><h3>Ruang Tumbuh Dago</h3><p>Senin–Jumat, 09.00–16.00</p><a href="https://maps.google.com/?q=Dago+Bandung" target="_blank" rel="noreferrer">Buka peta ↗</a></article><article><span>Yogyakarta</span><h3>Ruang Tumbuh Kotabaru</h3><p>Senin–Sabtu, 09.00–15.00</p><a href="https://maps.google.com/?q=Kotabaru+Yogyakarta" target="_blank" rel="noreferrer">Buka peta ↗</a></article></div></section>
  <section id="membership" class="join-section"><div><div class="section-kicker">06 / mulai sekarang</div><h2>Ruang tumbuh dimulai dari <em>satu keputusan.</em></h2></div><a class="button button-light" href="https://wa.me/6281234567890?text=Halo%20Ruang%20Tumbuh%2C%20saya%20ingin%20menjadi%20anggota." target="_blank" rel="noreferrer">Tanya cara bergabung</a></section>
  @include('partials.member-contact')
</main>
<footer class="site-footer"><div class="footer-contact"><div class="footer-contact-copy"><h2>KSP Dharma Siaga</h2><p class="footer-address">Denpasar, Bali<br>Alamat kantor resmi akan diperbarui setelah data layanan dikonfirmasi.</p><p class="footer-legal">Informasi layanan dan data indikatif pada situs ini disediakan untuk kebutuhan informasi anggota. Silakan hubungi kantor koperasi untuk informasi resmi.</p></div><div class="footer-contact-side"><a class="footer-phone" href="https://wa.me/6281234567890" target="_blank" rel="noreferrer"><span class="phone-icon" aria-hidden="true">☎</span><span><small>TANYA DHARMA SIAGA</small><strong>WhatsApp layanan</strong></span></a><div class="footer-socials"><a href="https://wa.me/6281234567890" target="_blank" rel="noreferrer" aria-label="WhatsApp">WA</a><a href="{{ route('blog.index') }}" aria-label="Catatan koperasi">NEWS</a><a href="{{ route('pages.about') }}" aria-label="Tentang KSP Dharma Siaga">INFO</a></div></div></div><div class="footer-bottom"><span>Copyright © 2026 KSP Dharma Siaga</span><span><a href="{{ route('pages.about') }}">Tentang</a> · <a href="{{ route('pages.reports') }}">Laporan</a> · <a href="{{ route('pages.branches') }}">Kantor cabang</a></span></div></footer>
<a class="whatsapp" href="https://wa.me/6281234567890?text=Halo%20Ruang%20Tumbuh" target="_blank" rel="noreferrer" aria-label="Hubungi Ruang Tumbuh melalui WhatsApp"><img src="https://static.whatsapp.net/rsrc.php/yJ/r/twC7frrXavH.svg" alt="" width="28" height="28"></a>
<dialog class="promo" data-promo><button class="dialog-close" data-promo-close aria-label="Tutup promosi">×</button><p class="eyebrow">Untuk anggota baru</p><h2>Mulai dari percakapan kecil.</h2><p>Konsultasikan kebutuhan keanggotaan Anda dengan tim kami.</p><a class="button" href="#membership" data-promo-close>Hubungi tim koperasi</a></dialog>
@endsection
